version: '3'

services:
  limiter-api:
    build: ./limiter-api
    ports:
      - "8080:8080"
    networks:
      - notifyme-network
  notifyme-api:
    build: ./notifyme-api
    ports:
      - "3030:3030"
    networks:
      - notifyme-network

networks:
  notifyme-network:
    driver: bridge
